services:
  docuforge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docuforge
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ROOT_DIR=/app
      - DOCUFORGE_ASSETS_REPO=https://github.com/Prixeree/docuforge-assets.git
    volumes:
      - .:/app/docuforge
      - docuforge_media:/app/docuforge-assets
    restart: unless-stopped

volumes:
  docuforge_media:
    name: docuforge_media
